### PR TITLE
Updated depracted values and imports

### PR DESCRIPTION
**Pull request by leolaboy**

### CODE REVIEW

**Comment by chihchunhsu** [comment]
Thanks @leolaboy! Which version of numpy and Python are you testing? Have you tested different numpy versions if that is backward compatible?

**Comment by leolaboy** [comment]
I used Python 3.12 but I haven't tested it with previous version of Numpy yet. I did however notice that it is causing issues with the newer Python versions.

**Comment by chihchunhsu** [comment]
Okay. Maybe we can handle this on top of your changes. Thanks for this effort! I will test older versions later when I get a chance.

**Comment by leolaboy** [comment]
Hello again! I just wanted to give you an update that I was able to test the changes with version 3.9.13 and didn't run into any issues with the changes. I didn't test the "clobber" to "overwrite" change since that should change along with the astropy module.

**Comment by chihchunhsu** [comment]
Thanks for looking into this!

**Pull request merged**
